[phases.setup]
nixPkgs = [
  "python311",
  "gcc",
  "freetype",
  "pkg-config",
  "zlib",
  "libjpeg",
  "libpng",
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
]

[start]
cmd = "python startup.py && python scheduler.py"
